In [38]:
import sys, os
import numpy as np

sys.path.insert(0, os.path.abspath("../src"))

from mini_torch.stats import sample_mean, center

In [39]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
X_mean = sample_mean(X, axis=1, keepdims=True)

In [49]:
X_mean

array([[2.],
       [5.]])

In [50]:
center(X, axis=1)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [53]:
X - X_mean == center(X, axis=1)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [54]:
X, X_mean, X - X_mean

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[2.],
        [5.]]),
 array([[-1.,  0.,  1.],
        [-1.,  0.,  1.]]))