In [23]:
import sys, os
import numpy as np
from math import prod

sys.path.insert(0, os.path.abspath("../src"))

from mini_torch.stats import sample_mean, center, sample_variance, sample_std

In [24]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [25]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
X_mean = sample_mean(X, axis=1, keepdims=True)

In [27]:
X_mean

array([[2.],
       [5.]])

In [28]:
center(X, axis=1)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [29]:
X - X_mean == center(X, axis=1)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [30]:
X, X_mean, X - X_mean

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[2.],
        [5.]]),
 array([[-1.,  0.,  1.],
        [-1.,  0.,  1.]]))

In [34]:
sample_variance(X, axis=1, keepdims=False)

array([1., 1.])

In [35]:
sample_std(X, axis=1, keepdims=False)

array([1., 1.])